export {
  closeEventStore,
  countEvents,
  deleteStoredFiles,
  getDefaultEventStorePath,
  findLegacyEventStore,
  getLegacyEventStorePath,
  getFileEntry,
  listStoredFileFingerprints,
  openEventStore,
  readDepartedFileEvents,
  readEventStoreEvents,
  readEventStoreMeta,
  readEventStoreMetaValues,
  readEventStoreStoredFiles,
  readEventStoreSummary,
  readFileEvents,
  readStoredFileSnapshots,
  replaceFileEvents,
  replaceFilesEvents,
  serializeEventStoreFingerprint,
  vacuumEventStore,
  writeEventStoreMeta,
  type DeleteStoredFilesInput,
  type DeleteStoredFilesResult,
  type EventStoreDependencyFingerprint,
  type EventStoreFileEntry,
  type EventStoreFileFingerprint,
  type EventStoreFileSnapshot,
  type EventStoreStoredFile,
  type EventStoreSummary,
  type ReplaceFileEventsInput,
} from './event-store-administration.js';
export { computeEventContentHash, normalizeStoredEvent } from './event-store-codec.js';
export {
  runTransaction,
  type EventStore,
  type LoadEventStoreSqliteModule,
} from './event-store-database.js';
export {
  EVENT_STORE_SCHEMA_VERSION,
  EventStoreSchemaVersionError,
  isSupportedSchemaVersion,
  MIGRATION_BATCH_SIZE,
  migrateSchemaV1ToV2,
  migrateSchemaV2ToV3,
} from './event-store-schema.js';
